// <auto-generated />
using System;
using System.Globalization;
using System.Resources;

namespace DupFree.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    internal static class Resources
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal static ResourceManager ResourceManager {
            get {
                if (resourceMan == null) {
                    resourceMan = new ResourceManager("DupFree.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture {
            get { return resourceCulture!; }
            set { resourceCulture = value; }
        }

        // auto-generated property accessors
        public static string PermissionDeniedTitle => ResourceManager.GetString("PermissionDeniedTitle", resourceCulture) ?? string.Empty;
        public static string PermissionDeniedMessage => ResourceManager.GetString("PermissionDeniedMessage", resourceCulture) ?? string.Empty;
        public static string Settings => ResourceManager.GetString("Settings", resourceCulture) ?? string.Empty;
        public static string FileSizeLimits => ResourceManager.GetString("FileSizeLimits", resourceCulture) ?? string.Empty;
        public static string DuplicateDisplayLimit => ResourceManager.GetString("DuplicateDisplayLimit", resourceCulture) ?? string.Empty;
        public static string DeleteConfirmation => ResourceManager.GetString("DeleteConfirmation", resourceCulture) ?? string.Empty;
        public static string GridViewPictureSize => ResourceManager.GetString("GridViewPictureSize", resourceCulture) ?? string.Empty;
        public static string GridViewFilePathDisplay => ResourceManager.GetString("GridViewFilePathDisplay", resourceCulture) ?? string.Empty;
        public static string RecycleBinSize => ResourceManager.GetString("RecycleBinSize", resourceCulture) ?? string.Empty;
        public static string ScanTimerDebug => ResourceManager.GetString("ScanTimerDebug", resourceCulture) ?? string.Empty;
        public static string ApplyFileSizeLimits => ResourceManager.GetString("ApplyFileSizeLimits", resourceCulture) ?? string.Empty;
        public static string ApplyDuplicateLimit => ResourceManager.GetString("ApplyDuplicateLimit", resourceCulture) ?? string.Empty;
        public static string ApplyGridSize => ResourceManager.GetString("ApplyGridSize", resourceCulture) ?? string.Empty;
        public static string ApplySetting => ResourceManager.GetString("ApplySetting", resourceCulture) ?? string.Empty;
        public static string ApplyRecycleBinSize => ResourceManager.GetString("ApplyRecycleBinSize", resourceCulture) ?? string.Empty;
        public static string Browse => ResourceManager.GetString("Browse", resourceCulture) ?? string.Empty;
        public static string DuplicateFiles => ResourceManager.GetString("DuplicateFiles", resourceCulture) ?? string.Empty;
        public static string SimilarImages => ResourceManager.GetString("SimilarImages", resourceCulture) ?? string.Empty;
        public static string RecycleBin => ResourceManager.GetString("RecycleBin", resourceCulture) ?? string.Empty;
        public static string Help => ResourceManager.GetString("Help", resourceCulture) ?? string.Empty;
        public static string ResetToDefaults => ResourceManager.GetString("ResetToDefaults", resourceCulture) ?? string.Empty;
        // message strings
        public static string FileNotFoundFormat => ResourceManager.GetString("FileNotFoundFormat", resourceCulture) ?? string.Empty;
        public static string CouldNotOpenFileFormat => ResourceManager.GetString("CouldNotOpenFileFormat", resourceCulture) ?? string.Empty;
        public static string LogFileNotFound => ResourceManager.GetString("LogFileNotFound", resourceCulture) ?? string.Empty;
        public static string NothingToDelete => ResourceManager.GetString("NothingToDelete", resourceCulture) ?? string.Empty;
        public static string ConfirmDeleteIndividualFormat => ResourceManager.GetString("ConfirmDeleteIndividualFormat", resourceCulture) ?? string.Empty;
        public static string InvalidInputNumber => ResourceManager.GetString("InvalidInputNumber", resourceCulture) ?? string.Empty;
        public static string RecycleBinSizeAppliedFormat => ResourceManager.GetString("RecycleBinSizeAppliedFormat", resourceCulture) ?? string.Empty;
        public static string ErrorSavingFormat => ResourceManager.GetString("ErrorSavingFormat", resourceCulture) ?? string.Empty;
        public static string NoSelection => ResourceManager.GetString("NoSelection", resourceCulture) ?? string.Empty;
        public static string ConfirmDeleteMultipleFormat => ResourceManager.GetString("ConfirmDeleteMultipleFormat", resourceCulture) ?? string.Empty;
        public static string InvalidMinSize => ResourceManager.GetString("InvalidMinSize", resourceCulture) ?? string.Empty;
        public static string InvalidMaxSize => ResourceManager.GetString("InvalidMaxSize", resourceCulture) ?? string.Empty;
        public static string MinGreaterThanMax => ResourceManager.GetString("MinGreaterThanMax", resourceCulture) ?? string.Empty;
        public static string FileSizeLimitsAppliedFormat => ResourceManager.GetString("FileSizeLimitsAppliedFormat", resourceCulture) ?? string.Empty;
        public static string DuplicateLimitAppliedFormat => ResourceManager.GetString("DuplicateLimitAppliedFormat", resourceCulture) ?? string.Empty;
        public static string GridSizeAppliedRefreshFormat => ResourceManager.GetString("GridSizeAppliedRefreshFormat", resourceCulture) ?? string.Empty;
        public static string GridSizeAppliedSwitchFormat => ResourceManager.GetString("GridSizeAppliedSwitchFormat", resourceCulture) ?? string.Empty;
    }
}